### ISSUE TITLE
Unable to create an app instance

### ISSUE THREAD

**Issue by khaledboka** [cartologic/cartoview_dashboard#12]
Tried to create an app instance but no response and save button got disabled

<img width="1440" alt="screen shot 2017-11-29 at 10 56 13 am" src="https://user-images.githubusercontent.com/13452248/33366434-f3945ca0-d4f3-11e7-9e47-ef73e65e0e8d.png">

<img width="1440" alt="screen shot 2017-11-29 at 10 56 05 am" src="https://user-images.githubusercontent.com/13452248/33366444-fa9839b8-d4f3-11e7-83a8-e6f71ff63d39.png">

**Comment by hishamkaram** [comment]
fixed https://github.com/cartologic/cartoview_dashboard/commit/d1550c74fbd7bd7b089ef15f63e02d094c44c023
